// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"BabyDuck/token"
)

const (
	NoState    = -1
	NumStates  = 78
	NumSymbols = 90
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '"'
1: ' '
2: '!'
3: '?'
4: '"'
5: '0'
6: 'p'
7: 'r'
8: 'o'
9: 'g'
10: 'r'
11: 'a'
12: 'm'
13: 'm'
14: 'a'
15: 'i'
16: 'n'
17: 'e'
18: 'n'
19: 'd'
20: 'v'
21: 'a'
22: 'r'
23: 'p'
24: 'r'
25: 'i'
26: 'n'
27: 't'
28: 'w'
29: 'h'
30: 'i'
31: 'l'
32: 'e'
33: 'd'
34: 'o'
35: 'i'
36: 'f'
37: 'e'
38: 'l'
39: 's'
40: 'e'
41: 'v'
42: 'o'
43: 'i'
44: 'd'
45: 'i'
46: 'n'
47: 't'
48: 'f'
49: 'l'
50: 'o'
51: 'a'
52: 't'
53: '+'
54: '-'
55: '*'
56: '/'
57: '<'
58: '>'
59: '!'
60: '='
61: '{'
62: '}'
63: '='
64: '('
65: ')'
66: '['
67: ']'
68: ','
69: ';'
70: '.'
71: ':'
72: '_'
73: '\t'
74: '\n'
75: '\r'
76: ' '
77: '/'
78: '/'
79: '\n'
80: '/'
81: '*'
82: '*'
83: '*'
84: '/'
85: '1'-'9'
86: 'A'-'Z'
87: 'a'-'z'
88: '0'-'9'
89: .
*/
